version: '3.8'
services:
# 后端服务模块
  backend:
    build:
      # 指定构建环境为所在目录下的 ReactorHttp 文件夹
      context: ./ReactorHttp
      # 使用上面 context 下的 dockerfile 进行构建
      dockerfile: dockerfile
    volumes:
      - ./ReactorHttp:/app:delegated
    environment:
      PORT: "8080"
    ports:
      - "8080:8080"
    # 后端容器启动时执行 watch 脚本，上面的配置中已经设定好了相关的环
    command: /bin/sh -c "/app/dev/watch_build_restart.sh"
    # 如果镜像不包含 inotifytools，请在 Dockerfile 中安装 inotify-tools 或使用 host-side watch (下面有替代方法)